[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # ã‚«ãƒ¼ã‚½ãƒ«ä½ç½®ã®ã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆã«åˆã‚ã›ã¦ftã‚’åˆ‡ã‚Šæ›¿ãˆã‚‹
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # ã‚«ãƒ¼ã‚½ãƒ«ä½ç½®ã®ã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆã®ftã‚’åˆ¤å®šã™ã‚‹ãƒ©ã‚¤ãƒ–ãƒ©ãƒª
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ã‚«ãƒ©ãƒ¼ã‚¹ã‚­ãƒ¼ãƒ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme è¨­å®šã¯ source å¾Œã«è¡Œã†å¿…è¦ãŒã‚ã‚‹ã®ã§ VimEnter ã§è¡Œã†ã€‚
  " ä½†ã— Colorscheme ã‚¤ãƒ™ãƒ³ãƒˆã®ç™ºç”ŸãŒæŠ‘åˆ¶ã•ã‚Œãªã„ã‚ˆã† nented ã‚’ä»˜ã‘ã‚‹ã€‚
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]] # è£œå®Œ
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  " deoplete ã‚’ä½¿ã†
  let g:deoplete#enable_at_startup = 1
  " smartcase ã‚’ä½¿ã†
  let g:deoplete#enable_smart_case = 1
  " è£œå®ŒãŒæœ‰åŠ¹ã«ãªã‚‹æ–‡å­—æ•°
  let g:deoplete#auto_completion_start_length = 3

  " <TAB> : è£œå®Œ
  inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
'''

[[plugins]] # ã‹ã£ã“ã„ã„ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ãƒ©ã‚¤ãƒ³ï¼ˆPowerlineã¯ã¾ã NeoVimã«å¯¾å¿œã—ã¦ã„ãªã„ã£ã½ã„ï¼‰
repo = 'itchyny/lightline.vim'
hook_add = '''
  " ã‚ã¾ã‚Šãƒ•ã‚©ãƒ³ãƒˆä¾å­˜ã®ã‚»ãƒ‘ãƒ¬ãƒ¼ã‚¿ã‚’ä½¿ã†ã¨ä½•ã‹ã¨ã‚ã‚“ã©ãã•ã„ã®ã§ä½¿ã‚ãªã„ã“ã¨ã«ã™ã‚‹
  let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'component': {
    \   'readonly': '%{&readonly?"ğŸ”’":""}',
    \ },
    \ 'subseparator': { 'left': "|", 'right': "|" }
    \ }
'''

[[plugins]] # ã„ã‚ã„ã‚ã‚µã‚¯ã‚µã‚¯ç§»å‹•
repo = 'tpope/vim-unimpaired'

[[plugins]] # æœ€è¿‘ä½¿ã£ãŸãƒ•ã‚¡ã‚¤ãƒ«ã‚’è¨˜éŒ²ã™ã‚‹
repo = 'Shougo/neomru.vim'

[[plugins]] # ã™ã”ã„ã‚„ã¤
repo = 'Shougo/denite.nvim'
hook_add = '''
  " æœ€è¿‘ä½¿ç”¨ã—ãŸãƒ•ã‚¡ã‚¤ãƒ«ä¸€è¦§ File Recent
  nnoremap <silent> <Space>fr :<C-u>Denite file_mru<CR>
'''

[[plugins]] # flowtype
repo = 'flowtype/vim-flow'
on_ft = 'javascript'

[[plugins]] # es6 ã‚³ãƒ¼ãƒ‰ãƒã‚¤ãƒ©ã‚¤ãƒˆ
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_add = '''
  let g:javascript_plugin_jsdoc = 1
  let g:javascript_plugin_flow = 1
'''

[[plugins]] # jsx ã‚³ãƒ¼ãƒ‰ãƒã‚¤ãƒ©ã‚¤ãƒˆ
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
depends = 'vim-javascript'
hook_add = '''
  let g:jsx_ext_required = 0
'''

[[plugins]] # ã‚·ãƒ³ã‚¿ãƒƒã‚¯ã‚¹ãƒã‚§ãƒƒã‚¯ã¨ã‹ã™ã‚‹ã‚„ã¤
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
  let g:neomake_javascript_enabled_makers = ['eslint']
'''

[[plugins]] # ãƒ­ãƒ¼ã‚«ãƒ«ã®eslintã‚’ä½¿ã†ã‚„ã¤
repo = 'benjie/neomake-local-eslint.vim'
on_ft = 'javascript'
depends = 'neomake'

[[plugins]] # ã‚¤ãƒ³ãƒ‡ãƒ³ãƒˆã‚’è¦‹ã‚„ã™ãã™ã‚‹ã‚„ã¤
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup=1
  let g:indent_guides_start_level=2
  let g:indent_guides_auto_colors=0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=236
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=235
  let g:indent_guides_color_change_percent = 30
  let g:indent_guides_guide_size = 1
'''
